vich_uploader:
  db_driver: orm

  mappings:
    post:
      uri_prefix: /assets/images/uploads
      upload_destination: "%kernel.project_dir%/public/assets/images/uploads"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
